### ISSUE TITLE
Q: Are none ARM-Cortex PR's with svd's welcome?

### ISSUE THREAD

**Issue by JohnBerg60** [cmsis-svd/cmsis-svd-data#28]
The title says it all.

I have some AVR ATMega svd files, converted from asdf, and some TI MSP 430 svd files also converted.

**Comment by BenBE** [comment]
Looking at the [data folder](https://github.com/posborne/cmsis-svd/tree/master/data) I'd spontaneously answer "yes". Especially as there already are some Atmel and TI chips present there …

**Comment by posborne** [comment]
@JohnBerg60 Contributions of SVD files with appropriate licenses compatible with the project as described in the README are welcome.  We do have some emergent rules we generally try to follow in that we target direct inclusion in the project of SVDs from vendors (when the license allows).  We don't generally patch SVDs with issues here but encourage those to be reported and updated by the originating vendor (more-or-less upstreaming fixes).  This is a bit challenging but seems the right way to go in general.
